# Generated by Django 5.2.17 on 2026-08-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='cma_session_id',
            field=models.CharField(blank=True, default='', help_text="Managed Agents session id. Blank until the thread's first answer.", max_length=64),
        ),
    ]
