# Generated by Django 5.2.17 on 2026-08-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_thread_cma_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Set by an explicit rename. Blank means derive it from the first message.', max_length=120),
        ),
    ]
