"""Chat threads, stored in our own database.

WHY WE STORE THESE OURSELVES

assistant-ui offers a hosted service (Assistant Cloud) that does exactly this,
and it is free at our scale. We are not using it, for three reasons worth
recording so nobody re-opens the question mid-hackathon:

1. It would put student chat history on a third party. PRD §9 is strict about
   personal data, and answers here can quote a student's Canvas assignments.
2. It bypasses Django rather than integrating with it — threads would live in
   their Postgres, so the planner could not read conversation history without a
   cross-service call, and `history` in `AskSerializer` exists precisely so it
   can.
3. `@assistant-ui/react-native` does not export the cloud thread-list adapter
   anyway, so the client-side adapter has to be hand-written either way. The
   cloud would have saved us the database, not the wiring.

SCOPING

Same model as apps/personal: an **anonymous session id**, not a Django user
(tasklist §1). Every query in the views filters on it. Threads are keyed by
`(session_id, client_id)` rather than by the client's id alone, so one session
can never read or overwrite another's thread by guessing an id — see the
unique constraint below.
"""

from __future__ import annotations

from django.db import models


class Thread(models.Model):
    """One conversation in the sidebar.

    The title is not stored. The app derives it from the first user message
    (`threadTitle` in frontend/app/lib/chatThreads.ts), and a stored copy would
    be one more thing to keep in sync for no gain.
    """

    # The app generates thread ids locally (assistant-ui's `generateId()`) the
    # moment someone taps "New Chat", before the server has heard of the
    # thread. Keeping that id as a plain column — rather than the primary key —
    # means two sessions can generate the same string without colliding, and
    # makes it impossible to reach another session's thread by guessing.
    client_id = models.CharField(
        max_length=64,
        help_text="Thread id generated by the app. Unique per session, not globally.",
    )
    session_id = models.CharField(
        max_length=128,
        db_index=True,
        help_text="Anonymous session this thread belongs to. Never a real user id.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    # Drives the sidebar's ordering, so it updates whenever messages are saved.
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["session_id", "client_id"],
                name="unique_thread_per_session",
            )
        ]
        # Most recent first — the order the sidebar wants, so no client sort.
        ordering = ["-updated_at"]

    def __str__(self) -> str:
        # Truncated session id: this string reaches logs and the admin.
        return f"Thread {self.client_id} (session {self.session_id[:8]}…)"


class Message(models.Model):
    """One turn in a thread.

    `content` holds assistant-ui's message *parts* array verbatim rather than a
    plain string. A single assistant turn is a list of parts — the answer text
    plus one "source" part per citation (see lib/assistantAdapter.ts) — so
    flattening it to text would throw away every citation the moment a thread
    was reloaded from the database.
    """

    class Role(models.TextChoices):
        USER = "user", "User"
        ASSISTANT = "assistant", "Assistant"

    thread = models.ForeignKey(
        Thread,
        # Deleting a thread deletes its messages. Also what makes the
        # delete-a-session path in the views complete rather than partial.
        on_delete=models.CASCADE,
        related_name="messages",
    )
    role = models.CharField(max_length=16, choices=Role.choices)
    content = models.JSONField(
        help_text="assistant-ui message parts, e.g. [{type: 'text', ...}, {type: 'source', ...}].",
    )
    # Explicit ordering rather than relying on insertion order or created_at:
    # a whole thread is saved in one request, so every row in that batch would
    # share a timestamp to the microsecond.
    position = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["thread", "position"],
                name="unique_message_position_per_thread",
            )
        ]
        ordering = ["position"]

    def __str__(self) -> str:
        return f"{self.get_role_display()} #{self.position} in {self.thread.client_id}"
