"""Chat threads, stored in our own database.

Not assistant-ui's hosted Assistant Cloud, though it is free at our scale, for
three reasons worth recording so nobody re-opens the question mid-hackathon:

1. It would put student chat history — which can quote Canvas assignments — on
   a third party, and PRD §9 is strict about personal data.
2. Threads would live in their Postgres, so the planner could not read history
   without a cross-service call, which is what `history` in `AskSerializer` is
   for.
3. `@assistant-ui/react-native` does not export the cloud thread-list adapter,
   so the client adapter is hand-written either way.

Scoped by anonymous session id, not a Django user (tasklist §1). Threads are
keyed `(session_id, client_id)` rather than by the client's id alone, so one
session cannot read or overwrite another's thread by guessing an id.
"""

from __future__ import annotations

from django.db import models


class Thread(models.Model):
    """One conversation in the sidebar.

    The title is not stored: the app derives it from the first user message
    (`threadTitle` in frontend/app/lib/chatThreads.ts).
    """

    # A plain column rather than the primary key, because the app generates
    # these locally before the server has heard of the thread: two sessions can
    # then produce the same string without colliding.
    client_id = models.CharField(
        max_length=64,
        help_text="Thread id generated by the app. Unique per session, not globally.",
    )
    session_id = models.CharField(
        max_length=128,
        db_index=True,
        help_text="Anonymous session this thread belongs to. Never a real user id.",
    )
    # The Managed Agents session this thread's answers run in. Blank until the
    # first question; after that the same session is reused, which is what lets a
    # follow-up ("is that still current?") see the previous turn's tool results
    # instead of searching again from scratch.
    #
    # Two stores, deliberately: this row stays authoritative for what the app
    # renders, and the session is what the model sees. A session that has been
    # archived or deleted on Anthropic's side leaves this string dangling, so the
    # planner treats an unusable id as "start a new session" rather than an error.
    cma_session_id = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text="Managed Agents session id. Blank until the thread's first answer.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    # Drives the sidebar's ordering.
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["session_id", "client_id"],
                name="unique_thread_per_session",
            )
        ]
        # The order the sidebar wants, so it never has to sort client-side.
        ordering = ["-updated_at"]

    def __str__(self) -> str:
        # Truncated session id: this string reaches logs and the admin.
        return f"Thread {self.client_id} (session {self.session_id[:8]}…)"


class Message(models.Model):
    """One turn in a thread.

    `content` holds assistant-ui's message *parts* array verbatim: an assistant
    turn is answer text plus one "source" part per citation (see
    lib/assistantAdapter.ts), so flattening it to a string would throw away
    every citation on reload.
    """

    class Role(models.TextChoices):
        USER = "user", "User"
        ASSISTANT = "assistant", "Assistant"

    thread = models.ForeignKey(
        Thread,
        # What makes the delete path in the views complete rather than partial.
        on_delete=models.CASCADE,
        related_name="messages",
    )
    role = models.CharField(max_length=16, choices=Role.choices)
    content = models.JSONField(
        help_text="assistant-ui message parts, e.g. [{type: 'text', ...}, {type: 'source', ...}].",
    )
    # Explicit rather than relying on created_at: a whole thread is saved in one
    # request, so every row in that batch shares a timestamp to the microsecond.
    position = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["thread", "position"],
                name="unique_message_position_per_thread",
            )
        ]
        ordering = ["position"]

    def __str__(self) -> str:
        return f"{self.get_role_display()} #{self.position} in {self.thread.client_id}"
