/**
 * This file and backend/apps/core/serializers.py describe the same JSON
 * (contract in tasklist.md §2). Change one, change the other — a mismatch is
 * invisible until it breaks in the app.
 */

/**
 * Every field is required, and "missing" is spelled `null` (or `''` for a url)
 * rather than `undefined`: the backend may omit fields, but `ask()` in api.ts
 * fills the gaps first, so components never write `citation.source ?? '…'`.
 */
export type Citation = {
  title: string
  /** Empty string when the source has no public URL. */
  url: string
  /** e.g. "Courses", "CMU Eats", "TartanConnect". */
  source: string
  /** Both timestamps must be surfaced in the UI (PRD §9). */
  indexed_at: string | null
  verified_at: string | null
  is_mock: boolean
}

/**
 * Which tool families ran, for the mode chips. Fixed vocabulary: the backend
 * validates `modes_used` against the same list (MODES in
 * backend/apps/tools/registry.py), so an uncovered string means they drifted.
 */
export type Mode =
  | 'rag'
  | 'courses'
  | 'dining'
  | 'events'
  | 'maps'
  | 'web_verify'
  | 'personal'

/** One earlier turn, replayed so follow-up questions have context. */
export type HistoryMessage = {
  role: 'user' | 'assistant'
  content: string
}

/** POST /api/ask/ request body. */
export type AskRequest = {
  query: string
  /**
   * Optional: without it the backend answers from public sources only. With
   * it, the user's connected sources are available to the planner.
   */
  session_id?: string
  /** Prior turns, oldest first. */
  history?: HistoryMessage[]
}

export type AskResponse = {
  answer: string
  citations: Citation[]
  modes_used: Mode[]
  /** A caveat to show above the answer, or null when there is nothing to flag. */
  note: string | null
}

/** One row of GET /api/sources/ — the credits and freshness list. */
export type Source = {
  name: string
  /** "public" is shared and indexable; "personal" is user-scoped (PRD §10). */
  tier: 'public' | 'personal'
  /** "Mock" is fixture data. */
  access: 'Crawl' | 'Live' | 'Token' | 'Mock'
  indexed_at: string | null
  /** False while the lane is a placeholder — don't imply coverage we lack. */
  implemented?: boolean
  note?: string
}

/** GET /api/sources/ response body. */
export type SourcesResponse = {
  sources: Source[]
}

/**
 * `content` is assistant-ui's message *parts* array, not a string — answer text
 * plus one "source" part per citation, which is what lets citations survive a
 * reload. `unknown[]` because this file describes the wire and the parts are
 * assistant-ui's types; lib/chatThreads.ts is where the two meet.
 */
export type StoredMessage = {
  role: 'user' | 'assistant'
  content: unknown[]
}

/** `id` is generated by the app, not the server. */
export type StoredThread = {
  id: string
  messages: StoredMessage[]
  /** Server-side last-write time, ISO 8601. Orders the sidebar. */
  updated_at: string
}

/** GET /api/threads/ response body. */
export type ThreadListResponse = {
  threads: StoredThread[]
}

/** Every API failure uses this shape (tasklist §2). Show `message` to the user. */
export type ApiError = {
  error: {
    code: string
    message: string
  }
}
