# Generated by Django 5.2.17 on 2026-08-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous session this credential belongs to. Never a real user id.', max_length=128)),
                ('provider', models.CharField(choices=[('canvas', 'Canvas'), ('ed', 'Ed Discussion'), ('stellic', 'Stellic (uploaded audit)')], max_length=32)),
                ('encrypted_token', models.TextField(help_text='Fernet ciphertext. Read it through get_token(), never directly.')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When we last pulled data from this source. Shown in the connectors UI.', null=True)),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('session_id', 'provider'), name='unique_connection_per_session_provider')],
            },
        ),
    ]
