# Generated by Django 5.2.17 on 2026-08-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='encrypted_token',
            field=models.TextField(help_text='Fernet ciphertext of a JSON credential. Read it through get_credential(), never directly.'),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='provider',
            field=models.CharField(choices=[('canvas', 'Canvas'), ('ed', 'Ed Discussion'), ('stellic', 'Stellic (uploaded audit)'), ('piazza', 'Piazza'), ('gradescope', 'Gradescope')], max_length=32),
        ),
    ]
